# Generated by Django 6.0.2 on 2026-02-16 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('session_time', models.DateTimeField(unique=True)),
                ('status', models.CharField(default='confirmed', max_length=20)),
            ],
            options={
                'ordering': ['session_time'],
            },
        ),
    ]
